print("Hello Python")
print(2+3)
print(2**3)

print("Hello Every body", end="+")
print("Welcome")
print("Python" * 3)
print(sum(range(1, 10)))
print("\t\tITGENIUS")
print("This is "+"Saturday")
print("Coffee","Tea","Milk")
